# Numpy

## Important Points
* Faster operations — because of its homogeneous nature
* Creation of n-dimensional arrays and operations on them

### Setting up numPy


In [1]:
import numpy as np

### nd-array
The primary reason that numpy is fast is because of the nd-array type that it uses to store and manipulate data
An ndarray is a generic multidimensional container for homogenous data

In [2]:
nparray = np.array([1,2,3,4])
print(nparray)

[1 2 3 4]


In [3]:
nparray.dtype

dtype('int64')

In [4]:
nparray.size

4

In [5]:
nparray.shape

(4,)

In [6]:
nparray.nbytes

32

## Comperision of List and Nparray by time complexity

In [7]:
%timeit pythonList = [i for i in range(10000)]

322 µs ± 28.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [8]:
 %timeit npList = np.arange(10000)

4.62 µs ± 76 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Generating data with numpy


* arange generates a list of numbers within the range of the digit passed

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

* **linspace** returns a set of linearly-spaced items within the range passed 

In [10]:
"""when we pass parameter here there are first 2 parameters which decide the starting and ending value and 3rd parameter decide how much there 
will be space there in divisio of equallay spaced parameters """
np.linspace(0, 10, 5)


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

* ones creates an array filled with ones And zeros creates an array filled with zeroes

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
"""zeros_like creates an array with the same size as the array passed as input. The generated array will have zeros as elements"""
np.zeros_like(np.arange(5))

array([0, 0, 0, 0, 0])

* **eye** function in Python is used to return a two-dimensional array with ones (1) on the diagonal and zeros (0) elsewhere.

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

* **empty** creates an array filled with garbage values, usually zeroes. The parameter passed as input is the size of the required array

In [15]:
np.empty(5)

array([1., 1., 1., 1., 1.])

### Indexing

* numpy follows the usual rules of Python when it comes to indexing and slicing.

In [16]:
"""Indexing"""
nparray

array([1, 2, 3, 4])

In [17]:
nparray[1]

2

In [18]:
nparray[-1]

4

* **Slicing**

In [19]:
"""Slicing arrays. Slicing in python means taking elements from one given index to another given index.
We pass slice instead of index like this: [start:end] ."""

nparray

array([1, 2, 3, 4])

In [20]:
nparray[1:2]

array([2])

In [21]:
nparray[:2]

array([1, 2])

In [22]:
nparray[:]

array([1, 2, 3, 4])

In [23]:
nparray[1:]

array([2, 3, 4])

In [24]:
largeArray = np.arange(100)

In [25]:
largeArray[::20]

array([ 0, 20, 40, 60, 80])

In [26]:
largeArray[1:10:2]

array([1, 3, 5, 7, 9])

In [27]:
largeArray[10:1:-2]

array([10,  8,  6,  4,  2])

An important thing to keep in mind while using slicing in numpy is that the slices are essentially references(views) and hence, 
any changes that you make to the sliced data will reflect in the parent. Lets look at an example

In [28]:
smallArray = largeArray[:10]

In [29]:
smallArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
largeArray[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
smallArray[0] = 789

In [32]:
smallArray

array([789,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [33]:
# You can see the change in the output
largeArray[:10]

array([789,   1,   2,   3,   4,   5,   6,   7,   8,   9])

## Axes

A numpy array can be multi-dimensional. It also gives you the ability to change an existing array to a shape of your liking provided that it meets multiple constraints
* **reshape lets you do exactly what the name says**

In [34]:
"""In reshape first attribute shows the number of rows and 2nd shows no of col it return 2D array"""
np.arange(1,9).reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [35]:
np.arange(1, 4).reshape(1,3)


array([[1, 2, 3]])

* **newaxis** is used to create a new axis in the data

* if the newaxis parameter is in the first position, then a new row vector will be generated 

* If its in the second position, then a column will be created with each of the elements being a separate vector.

In [36]:
"""When newaxis at first position"""
np.arange(1,5)[np.newaxis, : ]

array([[1, 2, 3, 4]])

In [37]:
"""When newaxis at 2nd position"""
np.arange(1,5)[:, np.newaxis ]

array([[1],
       [2],
       [3],
       [4]])

## Array Concatenation


Arrays can be concatenated in numpy using the concatenate method. The list of arrays to be concatenated is to be passed as input to the concatenate function.

In [38]:
np.concatenate([smallArray, largeArray])

array([789,   1,   2,   3,   4,   5,   6,   7,   8,   9, 789,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
        16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
        29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
        42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,
        55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,
        68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,
        81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
        94,  95,  96,  97,  98,  99])

In [39]:
np.concatenate([[1122],smallArray])

array([1122,  789,    1,    2,    3,    4,    5,    6,    7,    8,    9])

## Broadcasting
Operation of scalar vaue with numpy array

In [40]:
a = np.arange(1, 7)

In [41]:
a + 1

array([2, 3, 4, 5, 6, 7])

## Logical Operations
greater than, less than & equal to checks

In [42]:
x = np.array([1,3,4,4,5,6])
type(x)

numpy.ndarray

In [43]:
x > 5

array([False, False, False, False, False,  True])

In [44]:
x == 4

array([False, False,  True,  True, False, False])

In [45]:
np.any(x ==  4)

True

In [46]:
np.all(x == 6)

False

* you can use the sum() method as follows. It counts the number of True values in the array

In [47]:
 np.sum(x == 4)

2

In [48]:
np.any((x == 2) | (x == 3))

True

# Masking
Masking comes in; the True/False array can be passed into the array to provide only those values which meet the conditions

In [49]:
x[x == 4]

array([4, 4])

In [50]:
x[x > 2]

array([3, 4, 4, 5, 6])

# Fancy Indexing
Fancy indexing is nothing but the ability to access multiple elements of the array at once

In [54]:
type(x)
x

array([1, 3, 4, 4, 5, 6])

In [53]:
 x[[0, 2, 3]]

array([1, 4, 4])

# Sorting
 There are 2 ways you can sort a numpy array; in-place and by calling the numpy sort function that returns the sorted array

In [56]:
"""Shuffle funcution use to shuffle values randomly"""
np.random.shuffle(x)
x

array([3, 1, 6, 4, 4, 5])

In [60]:
"""First Methode
Calling np.sort on the array will return a copy of the array that is sorted and does not sort the array in place as demonstrated below"""
np.sort(x)

array([1, 3, 4, 4, 5, 6])

In [61]:
x

array([3, 1, 6, 4, 4, 5])

In [63]:
"""Second Methode """
x.sort()

In [64]:
x

array([1, 3, 4, 4, 5, 6])